#!/usr/bin/env perl
use Dzpl
    name => 'Term-EditorEdit',
    version => '0.0011',
    author => 'Robert Krimen <robertkrimen@gmail.com>',
    license => 'Perl5',
    copyright => 'Robert Krimen',

    require => q/
        Moo
        MooX::late
        Text::Clip
        Try::Tiny
        File::Temp

        [Test]
        Test::Most
    /,
;

{ plugin '@ROKR' }
